### ISSUE TITLE
Battery notification LED

### ISSUE THREAD

**Issue by voidzero** [M8s-dev/android_device_htc_m8qlul#2]
When plugged in, always shows green.

Solution is probably to include chargerled, and to start/stop it on plugin/plugout.

**Comment by voidzero** [comment]
Was fixed already some time ago.

**Comment by root-expert** [comment]
Looking today at the leds there seems to be a problem. 

When it's pluged in and charging it is using the function in light.c _set_speaker_light_locked_dual_ . Which means it displays two colors (green and red). I also checked the file _/sys/class/leds/indicator/ModeRGB_ and it shows "1ffff00" --> solid yellow.

In addition when it's plugged in and charging and there is a notification as well the led goes off instead of blinking green. Probably because it is already displaying green and it gets confused(??).

What is more, as we know from stock, when the battery is full (100%) the led turns solid green. In CM it actually turns green but in 90%. I searched the files and i couldn't find a file which shows the current percentage of the battery but only a file which shows when battery is full (maybe if we find the first file we can compare them and turn on green led when is required).

The only leds which seems to work fine is the "hey! low battery!". lol

I think we have to completely change the lights lib. I will try to incoporate chargeled code to the liblights code. It seems that it can solve the problem with the battery lights.

For the notification light i think we should completely remove the "set_speaker_light_locked_dual" function. Even thouh the kernel support dual colors i don't think HTC uses it and it is confusing the whole lights system.

Cheers
-root-expert.
